# application.properties de main

quarkus.azure-functions.app-name=func-feedback-core
quarkus.azure-functions.runtime.java-version=25
quarkus.http.root-path=api

quarkus.azure.keyvault.secret.endpoint=${QUARKUS_AZURE_KEYVAULT_SECRET_ENDPOINT:}

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.migrate-at-start=true

# Database
quarkus.datasource.db-kind=${FEEDBACK_DB_KIND:postgresql}
quarkus.datasource.jdbc.url=${FEEDBACK_DB_URL:${kv//FeedBackDBUrl:jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}}
quarkus.datasource.username=${FEEDBACK_DB_USER:${kv//FeedbackDBUser:sa}}
quarkus.datasource.password=${FEEDBACK_DB_PASSWORD:${kv//FeedBackDBPassword:sa}}

# Email
app.email.connection-string=${kv//FeedbackDBEmailConnectionString:}
app.admin-emails=${kv//FeedbackAdminEmailList:}
app.email.sender-address=${kv//FeedbackEmailSenderAddress:}
app.email.subject=${EMAIL_SUBJECT:Feedback de insatisfação recebido - FeedBack Platform}

# JWT
mp.jwt.verify.issuer=https://feedback-login.com.br/issuer
mp.jwt.verify.publickey=${kv//jwt-public-key:mock-key}
%test.mp.jwt.verify.publickey=mock-key
# ------------------------------------------------------------
# Perfil DEV - execução local com mvn quarkus:dev
# ------------------------------------------------------------
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:feedback_dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa

%dev.app.email.connection-string=endpoint=https://localhost;accesskey=mock
%dev.app.admin-emails=test@example.com
%dev.app.email.sender-address=test@example.com
%dev.app.email.subject=Feedback Dev

%dev.quarkus.otel.enabled=false
%dev.quarkus.otel.sdk.disabled=true
