quarkus.azure-functions.app-name=func-feedback-core
quarkus.azure-functions.runtime.java-version=25
quarkus.http.root-path=api

quarkus.azure.keyvault.secret.endpoint=${QUARKUS_AZURE_KEYVAULT_SECRET_ENDPOINT}

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.migrate-at-start=true

app.admin-emails=admin1@empresa.com,admin2@empresa.com

%test.quarkus.datasource.db-kind=${QUARKUS_DB_KIND:h2}
quarkus.datasource.db-kind=${QUARKUS_DB_KIND:PostgreSQL}
quarkus.datasource.jdbc.url=${kv//FeedBackDBUrl:jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
quarkus.datasource.username=${kv//FeedbackDBUser:sa}
quarkus.datasource.password=${kv//FeedBackDBPassword:sa}